name: Release Fragments

on:
  pull_request:
    branches:
      - release
    types: [closed]
  workflow_dispatch:

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Release fragments
        run: ./scripts/release.sh
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(grep '"version"' package.json | head -1 | sed -E 's/.*"version": "([^"]+)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: build/player-x-fragments-set.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}